[project]
name = "photobot"
version = "0.1.0"
description = "HW and SW for the photobot"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "asyncio>=4.0.0",
    "gpiozero>=2.0.1",
    "lgpio>=0.2.2.0",
    "rpi-hardware-pwm>=0.3.1",
]

[tool.uv]
required-environments = [
    "sys_platform == 'linux' and platform_machine == 'x86_64'",
    "sys_platform == 'linux' and platform_machine == 'aarch64'",
]
